### ISSUE TITLE
Instead of "Download", "DeleteList"!!!!!!!!!!

### ISSUE THREAD

**Issue by gladishd** [Geocodio/geocodio-library-node#28]
Type on to delete a list, run geocoder.list.deleteList(...) and pass in the ID of the list you'd like to delete. 
<img width="1440" alt="Screen Shot 2022-10-21 at 6 02 45 PM" src="https://user-images.githubusercontent.com/46453883/197295251-e587b6c9-3173-4be8-b00b-1e73dfe4a7bf.png">
By the way, if we have the county from the query can we also grab the county officials from that county as well?

**Comment by MiniCodeMonkey** [comment]
@gladishd Thanks for pointing this out! It has been corrected now.
