### ISSUE TITLE
bad response for the Africa side

### ISSUE THREAD

**Issue by rochelryu** [Geocodio/geocodio-library-node#5]
the response from library is not correct for many location in Africa. . (ex: Palm Club Hôtel, Boulevard des Martyrs, Abidjan).... the response wich return use the key word in the query not all key word

**Comment by MiniCodeMonkey** [comment]
Hi there,

Geocodio only supports geocoding locations in the US and Canada at this time.

Mathias

**Comment by rochelryu** [comment]
okay... i see
