### ISSUE TITLE
Axios Security Vulnerability

### ISSUE THREAD

**Issue by joshmossas** [Geocodio/geocodio-library-node#9]
There is a server-side request forgery vulnerability in versions of Axios before 0.21.1 ([related  NPM advisory](https://www.npmjs.com/advisories/1594)).

The Axios dependency should be updated to latest version to resolve this.

Screenshot from `npm audit`

![image](https://user-images.githubusercontent.com/31548851/104499820-445e6800-55a3-11eb-887c-37f209f9f1e0.png)

**Comment by atolchinsky** [comment]
Same issue here. Looks like there is an open PR (#8) to address this as of 9 days ago, but its yet to be merged.

**Comment by MiniCodeMonkey** [comment]
Thanks for letting us know!

The axios dependency has been updated now, and pushed with release v1.3.1
